### ISSUE TITLE
Error when running JqxList on a yaml file with `/` in the key

### ISSUE THREAD

**Issue by dkarter** [gennaro-tedesco/nvim-jqix#27]
Thank you for this plugin! I just discovered it and it looks very useful.

I just bumped into an error when running `JqxList` for the first time on a yaml file with `/` characters in the keys:

![CleanShot 2023-02-23 at 22 38 51@2x](https://user-images.githubusercontent.com/551858/221093329-4615d272-ccfc-420b-8eea-6bfe97a5ccf8.png)

```
E5108: Error executing lua .../nvim/site/pack/packer/opt/nvim-jqx/lua/nvim-jqx/jqx.lua:21: Vim:E492:
 Not an editor command: TrailingEmptyLines/echo line('.')
stack traceback:
        [C]: in function 'nvim_exec'
        .../nvim/site/pack/packer/opt/nvim-jqx/lua/nvim-jqx/jqx.lua:21: in function 'get_key_locatio
n'
        .../nvim/site/pack/packer/opt/nvim-jqx/lua/nvim-jqx/jqx.lua:64: in function 'populate_qf'
        ...nvim/site/pack/packer/opt/nvim-jqx/lua/nvim-jqx/init.lua:52: in function 'jqx_open'
        [string ":lua"]:1: in main chunk
```

Here's the file:

```yaml
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
```

FWIW it seems like `yq` is able to parse this file

<img width="397" alt="CleanShot 2023-02-23 at 22 45 56@2x" src="https://user-images.githubusercontent.com/551858/221094082-dd31fa67-c843-4d02-bfda-b6f9a9e58ebb.png">
